name = "DataInterpolationsND"
uuid = "4f1ef021-621a-47a5-ac8a-95402a2d1ea8"
version = "0.1.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[weakdeps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
DataInterpolationsNDSymbolicsExt = ["SymbolicUtils", "Symbolics"]

[compat]
Adapt = "4.3.0"
DataInterpolations = "8"
EllipsisNotation = "1.8.0"
ForwardDiff = "0"
KernelAbstractions = "0.9.34"
PrecompileTools = "1.0"
Random = "1"
RecipesBase = "1.3.4"
SafeTestsets = "0.1"
SymbolicUtils = "4"
Symbolics = "7"
Test = "1"
julia = "1"

[extras]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataInterpolations", "ForwardDiff", "Pkg", "Random", "SafeTestsets", "Symbolics", "Test", "SymbolicUtils"]
